using System;
using System.Collections.Generic;

namespace ProgrammaticFiltering.Models.Database
{
    public partial class VlapDomocallLog
    {
        public double? CallId { get; set; }
        public DateTime? Timestamp { get; set; }
        public string Campaign { get; set; }
        public string CallType { get; set; }
        public string Agent { get; set; }
        public string AgentName { get; set; }
        public string Disposition { get; set; }
        public string Ani { get; set; }
        public string CustomerName { get; set; }
        public string Dnis { get; set; }
        public long? CallTime { get; set; }
        public string BillTimeRounded { get; set; }
        public double? Cost { get; set; }
        public long? IvrTime { get; set; }
        public long? QueueWaitTime { get; set; }
        public long? RingTime { get; set; }
        public long? TalkTime { get; set; }
        public long? HoldTime { get; set; }
        public long? ParkTime { get; set; }
        public long? AfterCallWorkTime { get; set; }
        public string Transfers { get; set; }
        public double? Conferences { get; set; }
        public double? Holds { get; set; }
        public string Abandoned { get; set; }
        public string Recordings { get; set; }
        public DateTime? Date { get; set; }
        public string DateAndHour { get; set; }
        public double? DayOfMonth { get; set; }
        public string DayOfWeek { get; set; }
        public string HalfHour { get; set; }
        public string Hour { get; set; }
        public int? HourOfDay { get; set; }
        public string Month { get; set; }
        public string QuarterHour { get; set; }
        public long? Time { get; set; }
        public string TimeInterval { get; set; }
        public string TimestampMillisecond { get; set; }
        public int? Year { get; set; }
        public string AbandonRate { get; set; }
        public double? AniAreaCode { get; set; }
        public string AniCountry { get; set; }
        public double? AniCountryCode { get; set; }
        public string AniState { get; set; }
        public string CallSurveyResult { get; set; }
        public double? Calls { get; set; }
        public string CallsCompletedInIvr { get; set; }
        public string CallsTimedOutInIvr { get; set; }
        public string CampaignType { get; set; }
        public string Contacted { get; set; }
        public string DisconnectedFromHold { get; set; }
        public string DispositionGroupA { get; set; }
        public string DispositionGroupB { get; set; }
        public string DispositionGroupC { get; set; }
        public string DispositionPath { get; set; }
        public double? DnisAreaCode { get; set; }
        public string DnisCountry { get; set; }
        public double? DnisCountryCode { get; set; }
        public string DnisState { get; set; }
        public string IvrPath { get; set; }
        public string ListName { get; set; }
        public bool? LiveConnect { get; set; }
        public bool? NoPartyContact { get; set; }
        public string Notes { get; set; }
        public string ParentSessionId { get; set; }
        public string ServiceLevel { get; set; }
        public string SessionId { get; set; }
        public string Skill { get; set; }
        public long? SpeedOfAnswer { get; set; }
        public long? _3rdPartyTalkTime { get; set; }
        public long? ConferenceTime { get; set; }
        public long? ConsultTime { get; set; }
        public long? DialTime { get; set; }
        public long? HandleTime { get; set; }
        public long? ManualTime { get; set; }
        public double? Parks { get; set; }
        public double? PreviewInterrupted { get; set; }
        public double? PreviewInterruptedByCall { get; set; }
        public string PreviewInterruptedBySkillVm { get; set; }
        public long? PreviewTime { get; set; }
        public string QueueCallbackProcessing { get; set; }
        public string QueueCallbackRegistered { get; set; }
        public string QueueCallbackWaitTime { get; set; }
        public double? Rate { get; set; }
        public long? TalkTimeLessHoldAndPark { get; set; }
        public string TimeToAbandon { get; set; }
        public string TotalQueueTime { get; set; }
        public string VideoTime { get; set; }
        public double? Voicemails { get; set; }
        public string VoicemailsDeclined { get; set; }
        public string VoicemailsDeleted { get; set; }
        public long? VoicemailsHandleTime { get; set; }
        public string VoicemailsHandled { get; set; }
        public string VoicemailsReturnedCall { get; set; }
        public string VoicemailsTransferred { get; set; }
        public string AgentEmail { get; set; }
        public string AgentFirstName { get; set; }
        public string AgentGroup { get; set; }
        public string AgentId { get; set; }
        public string AgentLastName { get; set; }
        public string DestAgent { get; set; }
        public string DestAgentEmail { get; set; }
        public string DestAgentExtension { get; set; }
        public string DestAgentFirstName { get; set; }
        public string DestAgentGroup { get; set; }
        public string DestAgentLastName { get; set; }
        public string DestAgentName { get; set; }
        public int? Extension { get; set; }
        public string AccountNumber { get; set; }
        public string Address2 { get; set; }
        public string Age { get; set; }
        public string Amount { get; set; }
        public string AssignedAgent { get; set; }
        public string BusinessAnnualRevenue { get; set; }
        public string CampaignType1 { get; set; }
        public string CcExpiration { get; set; }
        public string CcHolderName { get; set; }
        public string CcToken { get; set; }
        public string CcType { get; set; }
        public string City { get; set; }
        public string Client { get; set; }
        public string Comments { get; set; }
        public string Company { get; set; }
        public string ContactCreateTimestamp { get; set; }
        public string ContactCreatedDateTime { get; set; }
        public double? ContactId { get; set; }
        public string ContactLastAgent { get; set; }
        public string ContactLastAgentDisposition { get; set; }
        public string ContactLastAgentDispositionDateTime { get; set; }
        public string ContactLastCampaign { get; set; }
        public string ContactLastDisposition { get; set; }
        public string ContactLastDispositionDateTime { get; set; }
        public string ContactModifiedDateTime { get; set; }
        public string ContactModifiedTimestamp { get; set; }
        public string DialAttempt { get; set; }
        public string Email { get; set; }
        public string Ex1 { get; set; }
        public string Ex2 { get; set; }
        public string Ex3 { get; set; }
        public string Ex4 { get; set; }
        public string Ex5 { get; set; }
        public string Fax { get; set; }
        public string FirstName { get; set; }
        public string Info1 { get; set; }
        public string Info10 { get; set; }
        public string Info11 { get; set; }
        public string Info12 { get; set; }
        public string Info13 { get; set; }
        public string Info14 { get; set; }
        public string Info15 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
        public string Info4 { get; set; }
        public string Info5 { get; set; }
        public string Info6 { get; set; }
        public string Info7 { get; set; }
        public string Info8 { get; set; }
        public string Info9 { get; set; }
        public string LastName { get; set; }
        public string ListName1 { get; set; }
        public string NumberOfEmployees { get; set; }
        public string Number1 { get; set; }
        public string Number2 { get; set; }
        public string Number3 { get; set; }
        public string Phone1Desc { get; set; }
        public string Phone2Desc { get; set; }
        public string PitchSection { get; set; }
        public string Program { get; set; }
        public string Q1 { get; set; }
        public string Q10 { get; set; }
        public string Q11 { get; set; }
        public string Q12 { get; set; }
        public string Q13 { get; set; }
        public string Q14 { get; set; }
        public string Q15 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4 { get; set; }
        public string Q5 { get; set; }
        public string Q6 { get; set; }
        public string Q7 { get; set; }
        public string Q8 { get; set; }
        public string Q9 { get; set; }
        public string QcsId { get; set; }
        public string Quantity { get; set; }
        public string ReadOnlySection { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingCompany { get; set; }
        public string ShippingFirstName { get; set; }
        public string ShippingLastName { get; set; }
        public string ShippingState { get; set; }
        public string ShippingTitle { get; set; }
        public string ShippingZip { get; set; }
        public string Sic { get; set; }
        public string SpokeTo { get; set; }
        public string State { get; set; }
        public string Street { get; set; }
        public string Title { get; set; }
        public string VendorName { get; set; }
        public string Zip { get; set; }
    }
}
